/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:044129a9-7918-4728-aaa6-789c7ded4e6d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_qXW5Wuoif",
    "aws_user_pools_web_client_id": "6jhaqse5h9e04h30hhqcjhcug3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pska7wsgm5aehbglnypddk6ofa.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-evwq7r7m6vbrbccz3ng5btybyy",
    "aws_user_files_s3_bucket": "amp-app-1234567890-imagestorage144236-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
